version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT:-6969}:${PORT:-6969}"
    environment:
      - PORT=${PORT:-6969}
      - HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@db:5432/bookdb}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn src.book_recommendations.main:app --host 0.0.0.0 --port ${PORT:-6969} --reload"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-bookdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-bookdb}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
